seed: 42
seed_path: "seeds/seeds_1.txt"
cuda: 1
predictor: 1
num_inference_steps: 11
guidance_scale: 7.5
height: 512
width: 512
output_folder: "results/cmaes_embedding_laion_partial_60"
n_tokens: 60
num_generations: 100
pop_size: 10
sigma: 0.1
max_score: 10.0
min_score: 1.0
fitness_weights: [2.0, 1.0, 1.0]
model_id: "sd-legacy/stable-diffusion-v1-5"