seed: 42
#seed_path: "seeds/seeds_1.txt"
seed_path: null
cuda: 0
predictor: 1
num_inference_steps: 11
guidance_scale: 7.5
height: 512
width: 512
output_folder: "results/hybrid"
num_generations: 3
pop_size: 10
sigma: 0.1
max_score: 10.0
min_score: 1.0
adam_iterations: 1
model_id: "sd-legacy/stable-diffusion-v1-5"